# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2017-01-01', verbose_name='date')),
                ('station', models.CharField(max_length=100, verbose_name='station')),
                ('line_number', models.IntegerField(default=1, verbose_name='subway line')),
                ('population0', models.IntegerField(default=0, verbose_name='0')),
                ('population1', models.IntegerField(default=0, verbose_name='1')),
                ('population2', models.IntegerField(default=0, verbose_name='2')),
                ('population3', models.IntegerField(default=0, verbose_name='3')),
                ('population4', models.IntegerField(default=0, verbose_name='4')),
                ('population5', models.IntegerField(default=0, verbose_name='5')),
                ('population6', models.IntegerField(default=0, verbose_name='6')),
                ('population7', models.IntegerField(default=0, verbose_name='7')),
                ('population8', models.IntegerField(default=0, verbose_name='8')),
                ('population9', models.IntegerField(default=0, verbose_name='9')),
                ('population10', models.IntegerField(default=0, verbose_name='10')),
                ('population11', models.IntegerField(default=0, verbose_name='11')),
                ('population12', models.IntegerField(default=0, verbose_name='12')),
                ('population13', models.IntegerField(default=0, verbose_name='13')),
                ('population14', models.IntegerField(default=0, verbose_name='14')),
                ('population15', models.IntegerField(default=0, verbose_name='15')),
                ('population16', models.IntegerField(default=0, verbose_name='16')),
                ('population17', models.IntegerField(default=0, verbose_name='17')),
                ('population18', models.IntegerField(default=0, verbose_name='18')),
                ('population19', models.IntegerField(default=0, verbose_name='19')),
                ('population20', models.IntegerField(default=0, verbose_name='20')),
                ('population21', models.IntegerField(default=0, verbose_name='21')),
                ('population22', models.IntegerField(default=0, verbose_name='22')),
                ('population23', models.IntegerField(default=0, verbose_name='23')),
                ('in_out', models.CharField(choices=[('on', '승차'), ('off', '하차')], default='on', max_length=10, verbose_name='on and off')),
            ],
        ),
    ]
