# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaymodel',
            name='line_number',
            field=models.CharField(default='1호선', max_length=10, verbose_name='subway line'),
        ),
    ]
